version: "3"
services:
# [TODO] Need to fix connecting to the local SQS service
#  merchant-sync-worker:
#    container_name: es_worker
#    build: ./es_worker
#    image: es_worker
#    volumes:
#      - './es_worker:/usr/src/app:cached'
#    env_file:
#      - local.env
#    depends_on:
#      - elasticsearch
#
#  sqs:
#    image: vsouza/sqs-local
#    container_name: gapi_sqs
#    ports:
#      - 9324:9324

  gini-auth:
    container_name: gini-auth
    build: ./gini-auth
    image: gini-auth
    volumes:
      - './gini-auth:/usr/src/app:cached'
    env_file: 
      - local.env
    depends_on:
      - db
    ports:
      - '3001:3001'
  cat-service:
    container_name: cat-service
    build: ./cat-service
    image: cat-service
    volumes:
      - './cat-service:/usr/src/app:cached'
    env_file:
      - local.env
    depends_on:
      - db
    ports:
      - '4000:4000'
  ap-backend:
    container_name: ap-backend
    build: ./ap-backend
    image: ap-backend
    volumes:
      - './ap-backend:/usr/src/app:cached'
    env_file:
      - local.env
    ports:
      - '3031:3031'
    depends_on:
      - db
  catch-duplicates-worker:
    container_name: backend-service
    build: ./backend-service
    image: backend-service
    volumes:
      - './backend-service:/usr/src/app:cached'
    env_file:
      - local.env
    ports:
      - '3003:3003'
    depends_on:
      - db
  app:
    container_name: gapi
    build: ./gapi/
    image: gapi
    ports:
      - '3000:3000'
    env_file:
      - ./local.env
    depends_on:
      - redis
      - db
      - elasticsearch
    volumes:
      - './gapi:/usr/src/app:cached'
    links:
      - db
      - redis
      - elasticsearch
    tty: true
    stdin_open: true

  db:
    container_name: gapi_db
    image: mysql:5.7.19
    volumes: [ "mysql_db_data:/data" ]
    ports:
      - '3306:3306'

  redis:
    container_name: gapi_redis
    image: redis:alpine
    volumes: [ "redis_db_data:/data" ]
    ports:
      - '6379:6379'

  elasticsearch:
    container_name: gapi_es
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    container_name: gapi_kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
volumes:
  mysql_db_data:
  redis_db_data:

